spring.application.name=summary
server.port=${SUMMARY_PORT:8070}

services.accounts.url=${ACCOUNTS_SERVICE_URL:http://localhost:8080}
services.cards.url=${CARDS_SERVICE_URL:http://localhost:9000}
services.loans.url=${LOANS_SERVICE_URL:http://localhost:8090}

spring.cloud.openfeign.client.config.default.connectTimeout=${FEIGN_CONNECT_TIMEOUT:2000}
spring.cloud.openfeign.client.config.default.readTimeout=${FEIGN_READ_TIMEOUT:5000}