# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/cards_db
spring.datasource.username=postgres
spring.datasource.password=Stuti0127@
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
  
# Testcontainers
spring.testcontainers.enabled=false

spring.liquibase.change-log=classpath:db/changelog/db-changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.contexts=development
spring.liquibase.default-schema=public

spring.sql.init.mode=never
spring.application.name=cards
server.port=9000
