-- PostgreSQL schema. Liquibase owns application schema initialization.
CREATE TABLE IF NOT EXISTS cards (
    card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number VARCHAR(20) NOT NULL,
    card_number VARCHAR(100) NOT NULL,
    card_type VARCHAR(100) NOT NULL,
    total_limit INT NOT NULL,
    amount_used INT NOT NULL,
    available_amount INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);
