spring.datasource.url=jdbc:postgresql://localhost:5432/accounts_db
spring.datasource.username=postgres
spring.datasource.password=Stuti0127@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db-changelog.xml
spring.liquibase.enabled=true
spring.jpa.properties.hibernate.default_schema=public
spring.liquibase.default-schema=public

