server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    driverClassName: org.postgresql.Driver
    username: postgres
    password: awasthistuti

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


