# Server port
server.port=8090

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loans_db
spring.datasource.username=postgres
spring.datasource.password=Stuti0127@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db-changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public

spring.sql.init.mode=never
spring.application.name=loans
